--Ajout des recettes dans la BD

INSERT INTO recette VALUES (0, 'Pâté chinois', 0);
INSERT INTO recette VALUES (1, 'Pâté chinois végétarien', 0);
INSERT INTO recette VALUES (2, 'Sauce spaghetti à la viande', 0);
INSERT INTO recette VALUES (3, 'Pizza trois fromages', 0);
INSERT INTO recette VALUES (4, 'Pizza pepperoni fromage', 0);
INSERT INTO recette VALUES (5, 'Tacos crevettes', 0);
INSERT INTO recette VALUES (6, 'Chili au boeuf', 0);
INSERT INTO recette VALUES (7, 'Lentille dahl', 0);
INSERT INTO recette VALUES (8, 'Tofu gochujang', 0);
INSERT INTO recette VALUES (9, 'Mijoté de pois chiche', 0);
INSERT INTO recette VALUES (10, 'Orzo aux tomates grillées  et féta', 0);
INSERT INTO recette VALUES (11, 'Pain aux bananes', 0);
INSERT INTO recette VALUES (12, 'Tajine de légumes', 0);
INSERT INTO recette VALUES (13, 'Tofu piri piri', 0);
INSERT INTO recette VALUES (14, 'Hamburger', 0);
INSERT INTO recette VALUES (15, 'Sauce au poulet et aux champignons', 0);
INSERT INTO recette VALUES (16, 'Cuisses de poulets rôties', 0);
INSERT INTO recette VALUES (17, 'Bâtonnes de poisson croustillants sans friture', 0);
INSERT INTO recette VALUES (18, 'Pâtes à la sauce tomate', 0);
INSERT INTO recette VALUES (19, 'Gravlax de saumon', 0);
INSERT INTO recette VALUES (20, 'Crêpes multigrains aux bleuets', 0);
INSERT INTO recette VALUES (21, 'Boeuf braisé', 0);
INSERT INTO recette VALUES (23, 'Ratatouille grillée en salade', 0);
INSERT INTO recette VALUES (24, 'Tartare de thon', 0);
INSERT INTO recette VALUES (26, 'Chaudrée de pommes de terre sans produits laitiers', 0);
INSERT INTO recette VALUES (28, 'Nouilles asiatiques au porc', 0);
INSERT INTO recette VALUES (29, 'Pâté mexicain', 0);
INSERT INTO recette VALUES (30, 'Tacos au poulet', 0);
INSERT INTO recette VALUES (31, 'Keftas de boeufs sur pain naan', 0);
INSERT INTO recette VALUES (32, 'Ragoût d''aubergine à la viande', 0);

--Ajout des ingrédients dans la BD

INSERT INTO aliment VALUES (0, 'Pomme de terre', 'Type');
INSERT INTO aliment VALUES (1, 'Beurre', 'Type');
INSERT INTO aliment VALUES (2, 'Lait', 'Type');
INSERT INTO aliment VALUES (3, 'Boeuf haché', 'Type');
INSERT INTO aliment VALUES (4, 'Oignon', 'Type');
INSERT INTO aliment VALUES (5, 'Maïs en crème', 'Type');
INSERT INTO aliment VALUES (6, 'Paprika', 'Type');
INSERT INTO aliment VALUES (7, 'Persil séché', 'Type');
INSERT INTO aliment VALUES (8, 'Crevette', 'Type');
INSERT INTO aliment VALUES (9, 'Patate douce', 'Type');
INSERT INTO aliment VALUES (10, 'Poivron rouge', 'Type');
INSERT INTO aliment VALUES (11, 'Porc haché', 'Type');
INSERT INTO aliment VALUES (12, 'Viande haché végétarienne', 'Type');
INSERT INTO aliment VALUES (13, 'Pois chiche', 'Type');
INSERT INTO aliment VALUES (14, 'Pâte de tomate', 'Type');
INSERT INTO aliment VALUES (15, 'Épinards', 'Type');
INSERT INTO aliment VALUES (16, 'Cari', 'Type');
INSERT INTO aliment VALUES (17, 'Huile de canola', 'Type');
INSERT INTO aliment VALUES (18, 'Sel', 'Type');
INSERT INTO aliment VALUES (19, 'Poivre', 'Type');
INSERT INTO aliment VALUES (20, 'Spaghetti', 'Type');
INSERT INTO aliment VALUES (21, 'Carotte', 'Type');
INSERT INTO aliment VALUES (22, 'Celeri', 'Type');
INSERT INTO aliment VALUES (23, 'Mozzarella', 'Type');
INSERT INTO aliment VALUES (24, 'Farine', 'Type');
INSERT INTO aliment VALUES (25, 'Sauce à pizza', 'Type');
INSERT INTO aliment VALUES (26, 'Pâte à pizza', 'Type');
INSERT INTO aliment VALUES (27, 'Ricotta', 'Type');
INSERT INTO aliment VALUES (28, 'Féta', 'Type');
INSERT INTO aliment VALUES (29, 'Pepperoni', 'Type');
INSERT INTO aliment VALUES (30, 'Tortilla de mais', 'Type');
INSERT INTO aliment VALUES (31, 'Mangue', 'Type');
INSERT INTO aliment VALUES (32, 'Coriandre', 'Type');
INSERT INTO aliment VALUES (33, 'Champignon', 'Type');
INSERT INTO aliment VALUES (34, 'Poudre de chili', 'Type');
INSERT INTO aliment VALUES (35, 'Haricot rouge', 'Type');
INSERT INTO aliment VALUES (36, 'Cumin', 'Type');
INSERT INTO aliment VALUES (37, 'Ail', 'Type');
INSERT INTO aliment VALUES (38, 'Piment jalapeno', 'Type');
INSERT INTO aliment VALUES (39, 'Café', 'Type');
INSERT INTO aliment VALUES (40, 'Tomates en dés', 'Type');
INSERT INTO aliment VALUES (41, 'Jus de lime', 'Type');
INSERT INTO aliment VALUES (42, 'Bouillon de boeuf', 'Type');
INSERT INTO aliment VALUES (43, 'Lentille rouge', 'Type');
INSERT INTO aliment VALUES (44, 'Huile de noix de coco', 'Type');
INSERT INTO aliment VALUES (45, 'Gingembre', 'Type');
INSERT INTO aliment VALUES (46, 'Garam masala', 'Type');
INSERT INTO aliment VALUES (47, 'Bouillon végétarien', 'Type');
INSERT INTO aliment VALUES (48, 'Lait de coco', 'Type');
INSERT INTO aliment VALUES (49, 'Goghujang', 'Type');
INSERT INTO aliment VALUES (50, 'Sauce soya', 'Type');
INSERT INTO aliment VALUES (51, 'Vinaigre de riz', 'Type');
INSERT INTO aliment VALUES (52, 'Tofu', 'Type');
INSERT INTO aliment VALUES (53, 'Fécule de maïs', 'Type');
INSERT INTO aliment VALUES (54, 'Broccoli', 'Type');
INSERT INTO aliment VALUES (55, 'Pois chiche', 'Type');
INSERT INTO aliment VALUES (56, 'Saumon', 'Type');
INSERT INTO aliment VALUES (57, 'Bleuet', 'Type');
INSERT INTO aliment VALUES (58, 'Graine de sésame', 'Type');
INSERT INTO aliment VALUES (59, 'Poudre à pâte', 'Type');
INSERT INTO aliment VALUES (60, 'Cassonade', 'Type');
INSERT INTO aliment VALUES (61, 'Extrait de vanille', 'Type');
INSERT INTO aliment VALUES (62, 'Boisson de soya', 'Type');
INSERT INTO aliment VALUES (63, 'Flocon davoine', 'Type');
INSERT INTO aliment VALUES (64, 'Sambal Oelek', 'Type');
INSERT INTO aliment VALUES (65, 'Orzo', 'Type');
INSERT INTO aliment VALUES (66, 'Sirop dérable', 'Type');
INSERT INTO aliment VALUES (67, 'Échalote', 'Type');
INSERT INTO aliment VALUES (68, 'Basilic', 'Type');
INSERT INTO aliment VALUES (69, 'Vinaigre de vin rouge', 'Type');
INSERT INTO aliment VALUES (70, 'Banane', 'Type');
INSERT INTO aliment VALUES (71, 'Bicarbonate de soude', 'Type');
INSERT INTO aliment VALUES (72, 'Oeuf', 'Type');
INSERT INTO aliment VALUES (73, 'Rutabaga', 'Type');
INSERT INTO aliment VALUES (74, 'Aubergine', 'Type');
INSERT INTO aliment VALUES (75, 'Courgette', 'Type');
INSERT INTO aliment VALUES (76, 'Pâte harissa', 'Type');
INSERT INTO aliment VALUES (77, 'Citron', 'Type');
INSERT INTO aliment VALUES (78, 'Olive verte', 'Type');
INSERT INTO aliment VALUES (79, 'Abricots séchés', 'Type');
INSERT INTO aliment VALUES (80, 'Vinaigre de vin blanc', 'Type');
INSERT INTO aliment VALUES (81, 'Ail en poudre', 'Type');
INSERT INTO aliment VALUES (82, 'Origan', 'Type');
INSERT INTO aliment VALUES (83, 'Sucre', 'Type');
INSERT INTO aliment VALUES (84, 'Laitue', 'Type');
INSERT INTO aliment VALUES (85, 'Ketchup', 'Type');
INSERT INTO aliment VALUES (86, 'Mayonnaise', 'Type');
INSERT INTO aliment VALUES (87, 'Moutarde', 'Type');
INSERT INTO aliment VALUES (88, 'Cornichon', 'Type');
INSERT INTO aliment VALUES (89, 'Pain hamburger', 'Type');
INSERT INTO aliment VALUES (90, 'Tomate', 'Type');
INSERT INTO aliment VALUES (91, 'Cheddar', 'Type');
INSERT INTO aliment VALUES (92, 'Champignon', 'Type');
INSERT INTO aliment VALUES (93, 'Poulet', 'Type');
INSERT INTO aliment VALUES (94, 'Dinde', 'Type');
INSERT INTO aliment VALUES (95, 'Pancetta', 'Type');
INSERT INTO aliment VALUES (96, 'Lait', 'Type');
INSERT INTO aliment VALUES (97, 'Sauge fraîche', 'Type');
INSERT INTO aliment VALUES (98, 'Muscade', 'Type');
INSERT INTO aliment VALUES (99, 'Parmesan', 'Type');
INSERT INTO aliment VALUES (100, 'Aiglefin', 'Type');
INSERT INTO aliment VALUES (101, 'Chapelure', 'Type');
INSERT INTO aliment VALUES (102, 'Cannelle', 'Type');
INSERT INTO aliment VALUES (103, 'Persil', 'Type');
INSERT INTO aliment VALUES (104, 'Olive noire', 'Type');
INSERT INTO aliment VALUES (105, 'Penne', 'Type');
INSERT INTO aliment VALUES (106, 'Rigatoni', 'Type');
INSERT INTO aliment VALUES (107, 'Pecorino', 'Type');
INSERT INTO aliment VALUES (108, 'Clou de girofle', 'Type');
INSERT INTO aliment VALUES (109, 'Menthe', 'Type');
INSERT INTO aliment VALUES (110, 'Graine de coriandre', 'Type');
INSERT INTO aliment VALUES (111, 'Orange', 'Type');
INSERT INTO aliment VALUES (112, 'Boeuf', 'Type');
INSERT INTO aliment VALUES (113, 'Bacon', 'Type');
INSERT INTO aliment VALUES (114, 'Vinaigne balsamique', 'Type');
INSERT INTO aliment VALUES (115, 'Romarin', 'Type');
INSERT INTO aliment VALUES (116, 'Flocon de piment fort', 'Type');
INSERT INTO aliment VALUES (117, 'Tomates cerises', 'Type');
INSERT INTO aliment VALUES (118, 'Thon', 'Type');
INSERT INTO aliment VALUES (119, 'Limes', 'Type');
INSERT INTO aliment VALUES (120, 'Câpre', 'Type');
INSERT INTO aliment VALUES (121, 'Poireaux', 'Type');
INSERT INTO aliment VALUES (122, 'Maïs', 'Type');
INSERT INTO aliment VALUES (123, 'Sauce tabasco', 'Type');
INSERT INTO aliment VALUES (124, 'Crème sure', 'Type');
INSERT INTO aliment VALUES (125, 'Yogourt', 'Type');
INSERT INTO aliment VALUES (126, 'Échalot française', 'Type');
INSERT INTO aliment VALUES (127, 'Pâte de sésame', 'Type');
INSERT INTO aliment VALUES (128, 'Sauce hoisin', 'Type');
INSERT INTO aliment VALUES (129, 'Nouille ramen', 'Type');
INSERT INTO aliment VALUES (130, 'Arachide', 'Type');
INSERT INTO aliment VALUES (131, 'Tomates cerises', 'Type');
INSERT INTO aliment VALUES (132, 'Huile d''olive', 'Type');
INSERT INTO aliment VALUES (133, 'Pain naan', 'Type');
INSERT INTO aliment VALUES (134, 'Avocats', 'Type');
INSERT INTO aliment VALUES (135, 'Assaisonnement au chili', 'Type');
INSERT INTO aliment VALUES (136, 'Curcuma', 'Type');
INSERT INTO aliment VALUES (137, 'Bouillon de légume', 'Type');
INSERT INTO aliment VALUES (138, 'Huile de sésame', 'Type');
INSERT INTO aliment VALUES (139, 'Thym', 'Type');
INSERT INTO aliment VALUES (140, 'Pâtes orzo', 'Type');
INSERT INTO aliment VALUES (141, 'Poudre à pâte', 'Type');
INSERT INTO aliment VALUES (142, 'Bouillon de poulet', 'Type');
INSERT INTO aliment VALUES (143, 'Vin blanc', 'Type');
INSERT INTO aliment VALUES (144, 'Ciboulette', 'Type');
INSERT INTO aliment VALUES (145, 'Estragon', 'Type');
INSERT INTO aliment VALUES (146, 'Beurre d''arachide', 'Type');
INSERT INTO aliment VALUES (147, 'Huile de piment', 'Type');
INSERT INTO aliment VALUES (148, 'Bok choy', 'Type');
INSERT INTO aliment VALUES (149, 'Relish', 'Type');
INSERT INTO aliment VALUES (150, 'Sauce aux piments', 'Type');
INSERT INTO aliment VALUES (151, 'fromage tex-mex râpé', 'Type');
INSERT INTO aliment VALUES (152, 'Coquille tacos', 'Type');
INSERT INTO aliment VALUES (153, 'Salsa', 'Type');
INSERT INTO aliment VALUES (154, 'Poivron vert', 'Type');
INSERT INTO aliment VALUES (155, 'Saucisses italiennes', 'Type');
INSERT INTO aliment VALUES (156, 'Oignons verts', 'Type');
INSERT INTO aliment VALUES (157, 'Jelapeños', 'Type');
INSERT INTO aliment VALUES (158, 'Vinaigre Blanc', 'Type');
INSERT INTO aliment VALUES (159, 'Crème 35 %', 'Type');
INSERT INTO aliment VALUES (160, 'Vin Rouge', 'Type');
INSERT INTO aliment VALUES (161, 'Miel', 'Type');
INSERT INTO aliment VALUES (162, 'Poivre Sichuan', 'Type');

--Ajout des recettes avec les aliments
INSERT INTO aliment_recette VALUES (0, 0);
INSERT INTO aliment_recette VALUES (1, 0);
INSERT INTO aliment_recette VALUES (2, 0);
INSERT INTO aliment_recette VALUES (3, 0);
INSERT INTO aliment_recette VALUES (4, 0);
INSERT INTO aliment_recette VALUES (5, 0);
INSERT INTO aliment_recette VALUES (6, 0);
INSERT INTO aliment_recette VALUES (7, 0);

INSERT INTO aliment_recette VALUES (0, 1);
INSERT INTO aliment_recette VALUES (1, 1);
INSERT INTO aliment_recette VALUES (2, 1);
INSERT INTO aliment_recette VALUES (12, 1);
INSERT INTO aliment_recette VALUES (4, 1);
INSERT INTO aliment_recette VALUES (5, 1);
INSERT INTO aliment_recette VALUES (6, 1);
INSERT INTO aliment_recette VALUES (7, 1);

-- https://www.ricardocuisine.com/recettes/5335-sauce-a-spaghetti-la-meilleure
INSERT INTO aliment_recette VALUES (3, 2);
INSERT INTO aliment_recette VALUES (4, 2);
INSERT INTO aliment_recette VALUES (21, 2);
INSERT INTO aliment_recette VALUES (22, 2);
INSERT INTO aliment_recette VALUES (14, 2);
INSERT INTO aliment_recette VALUES (18, 2);
INSERT INTO aliment_recette VALUES (19, 2);
INSERT INTO aliment_recette VALUES (155, 2);
INSERT INTO aliment_recette VALUES (132, 2);
INSERT INTO aliment_recette VALUES (37, 2);
INSERT INTO aliment_recette VALUES (90, 2);
INSERT INTO aliment_recette VALUES (42, 2);
INSERT INTO aliment_recette VALUES (82, 2);

-- https://www.ricardocuisine.com/recettes/2051-pizza-aux-trois-fromages
INSERT INTO aliment_recette VALUES (25, 3);
INSERT INTO aliment_recette VALUES (26, 3);
INSERT INTO aliment_recette VALUES (23, 3);
INSERT INTO aliment_recette VALUES (27, 3);
INSERT INTO aliment_recette VALUES (28, 3);

-- https://fantinomondello.ca/fr/recettes/pizza-pepperoni-fromage/113
INSERT INTO aliment_recette VALUES (25, 4);
INSERT INTO aliment_recette VALUES (26, 4);
INSERT INTO aliment_recette VALUES (23, 4);
INSERT INTO aliment_recette VALUES (29, 4);

-- https://www.ricardocuisine.com/recettes/8384-tacos-aux-crevettes-et-salsa-a-la-mangue
INSERT INTO aliment_recette VALUES (30, 5);
INSERT INTO aliment_recette VALUES (17, 5);
INSERT INTO aliment_recette VALUES (134, 5);
INSERT INTO aliment_recette VALUES (8, 5);
INSERT INTO aliment_recette VALUES (31, 5);
INSERT INTO aliment_recette VALUES (32, 5);
INSERT INTO aliment_recette VALUES (41, 5);
INSERT INTO aliment_recette VALUES (10, 5);
INSERT INTO aliment_recette VALUES (156, 5);

-- https://www.ricardocuisine.com/recettes/5762-chili-classique-au-boeuf
INSERT INTO aliment_recette VALUES (3, 6);
INSERT INTO aliment_recette VALUES (4, 6);
INSERT INTO aliment_recette VALUES (21, 6);
INSERT INTO aliment_recette VALUES (14, 6);
INSERT INTO aliment_recette VALUES (33, 6);
INSERT INTO aliment_recette VALUES (34, 6);
INSERT INTO aliment_recette VALUES (35, 6);
INSERT INTO aliment_recette VALUES (36, 6);
INSERT INTO aliment_recette VALUES (37, 6);
INSERT INTO aliment_recette VALUES (38, 6);
INSERT INTO aliment_recette VALUES (40, 6);
INSERT INTO aliment_recette VALUES (42, 6);
INSERT INTO aliment_recette VALUES (135, 6);

-- https://www.ricardocuisine.com/recettes/5684-dahl
INSERT INTO aliment_recette VALUES (43, 7);
INSERT INTO aliment_recette VALUES (21, 7);
INSERT INTO aliment_recette VALUES (15, 7);
INSERT INTO aliment_recette VALUES (16, 7);
INSERT INTO aliment_recette VALUES (44, 7);
INSERT INTO aliment_recette VALUES (45, 7);
INSERT INTO aliment_recette VALUES (46, 7);
INSERT INTO aliment_recette VALUES (47, 7);
INSERT INTO aliment_recette VALUES (48, 7);
INSERT INTO aliment_recette VALUES (18, 7);
INSERT INTO aliment_recette VALUES (136, 7);
INSERT INTO aliment_recette VALUES (137, 7);

-- https://www.google.com/search?q=Tofu+gochujang&rlz=1C5CHFA_enCA1092CA1092&oq=Tofu+gochujang&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDIHCAEQABiABDIMCAIQABgUGIcCGIAEMggIAxAAGBYYHjIICAQQABgWGB4yCAgFEAAYFhgeMggIBhAAGBYYHjIICAcQABgWGB4yCAgIEAAYFhgeMggICRAAGBYYHtIBBzY1N2owajeoAgiwAgE&sourceid=chrome&ie=UTF-8
INSERT INTO aliment_recette VALUES (52, 8);
INSERT INTO aliment_recette VALUES (49, 8);
INSERT INTO aliment_recette VALUES (50, 8);
INSERT INTO aliment_recette VALUES (51, 8);
INSERT INTO aliment_recette VALUES (17, 8);
INSERT INTO aliment_recette VALUES (54, 8); 
INSERT INTO aliment_recette VALUES (53, 8);
INSERT INTO aliment_recette VALUES (18, 8);
INSERT INTO aliment_recette VALUES (138, 8);
INSERT INTO aliment_recette VALUES (85, 8);
INSERT INTO aliment_recette VALUES (37, 8);
INSERT INTO aliment_recette VALUES (19, 8);

-- https://lacuisinedejeanphilippe.com/recipe/mijote-de-pois-chiches-epice/
INSERT INTO aliment_recette VALUES (13, 9);
INSERT INTO aliment_recette VALUES (21, 9);
INSERT INTO aliment_recette VALUES (4, 9);
INSERT INTO aliment_recette VALUES (37, 9);
INSERT INTO aliment_recette VALUES (40, 9);
INSERT INTO aliment_recette VALUES (42, 9);
INSERT INTO aliment_recette VALUES (19, 9);
INSERT INTO aliment_recette VALUES (77, 9);
INSERT INTO aliment_recette VALUES (132, 9);
INSERT INTO aliment_recette VALUES (46, 9);
INSERT INTO aliment_recette VALUES (66, 9);

-- https://stephaniecote.ca/orzo-aux-tomates-grillees-et-feta/
INSERT INTO aliment_recette VALUES (65, 10);
INSERT INTO aliment_recette VALUES (67, 10);
INSERT INTO aliment_recette VALUES (68, 10);
INSERT INTO aliment_recette VALUES (28, 10);
INSERT INTO aliment_recette VALUES (139, 10);
INSERT INTO aliment_recette VALUES (140, 10);
INSERT INTO aliment_recette VALUES (117, 10);
INSERT INTO aliment_recette VALUES (132, 10);
INSERT INTO aliment_recette VALUES (66, 10);
INSERT INTO aliment_recette VALUES (37, 10);
INSERT INTO aliment_recette VALUES (34, 10);
INSERT INTO aliment_recette VALUES (19, 10);
INSERT INTO aliment_recette VALUES (69, 10);

-- https://www.ricardocuisine.com/recettes/6085-pain-aux-bananes-ultra-moelleux
INSERT INTO aliment_recette VALUES (1, 11);
INSERT INTO aliment_recette VALUES (70, 11);
INSERT INTO aliment_recette VALUES (60, 11);
INSERT INTO aliment_recette VALUES (61, 11);
INSERT INTO aliment_recette VALUES (24, 11);
INSERT INTO aliment_recette VALUES (71, 11);
INSERT INTO aliment_recette VALUES (72, 11);
INSERT INTO aliment_recette VALUES (141, 11);
INSERT INTO aliment_recette VALUES (41, 11);
INSERT INTO aliment_recette VALUES (48, 11);

-- https://www.ricardocuisine.com/recettes/8021-tajine-de-legumes
INSERT INTO aliment_recette VALUES (21, 12);
INSERT INTO aliment_recette VALUES (74, 12);
INSERT INTO aliment_recette VALUES (75, 12);
INSERT INTO aliment_recette VALUES (79, 12);
INSERT INTO aliment_recette VALUES (77, 12);
INSERT INTO aliment_recette VALUES (78, 12);
INSERT INTO aliment_recette VALUES (76, 12);
INSERT INTO aliment_recette VALUES (14, 12);
INSERT INTO aliment_recette VALUES (73, 12);
INSERT INTO aliment_recette VALUES (132, 12);
INSERT INTO aliment_recette VALUES (10, 12);
INSERT INTO aliment_recette VALUES (136, 12);
INSERT INTO aliment_recette VALUES (36, 12);
INSERT INTO aliment_recette VALUES (110, 12);
INSERT INTO aliment_recette VALUES (55, 12);
INSERT INTO aliment_recette VALUES (137, 12);

-- https://www.boblechef.com/recettes/tofu-piri-piri
INSERT INTO aliment_recette VALUES (52, 13);
INSERT INTO aliment_recette VALUES (51, 13);
INSERT INTO aliment_recette VALUES (53, 13);
INSERT INTO aliment_recette VALUES (18, 13);
INSERT INTO aliment_recette VALUES (132, 13);
INSERT INTO aliment_recette VALUES (10, 13);
INSERT INTO aliment_recette VALUES (81, 13);
INSERT INTO aliment_recette VALUES (6, 13);
INSERT INTO aliment_recette VALUES (82, 13);
INSERT INTO aliment_recette VALUES (83, 13);
INSERT INTO aliment_recette VALUES (19, 13);

-- https://www.ricardocuisine.com/recettes/3607-hamburgers-doubles-a-l-americaine
INSERT INTO aliment_recette VALUES (3, 14);
INSERT INTO aliment_recette VALUES (84, 14);
INSERT INTO aliment_recette VALUES (85, 14);
INSERT INTO aliment_recette VALUES (86, 14);
INSERT INTO aliment_recette VALUES (87, 14);
INSERT INTO aliment_recette VALUES (88, 14);
INSERT INTO aliment_recette VALUES (89, 14);
INSERT INTO aliment_recette VALUES (90, 14);
INSERT INTO aliment_recette VALUES (91, 14);
INSERT INTO aliment_recette VALUES (4, 14);
INSERT INTO aliment_recette VALUES (149, 14);
INSERT INTO aliment_recette VALUES (60, 14);
INSERT INTO aliment_recette VALUES (158, 14);
INSERT INTO aliment_recette VALUES (19, 14);

-- https://ici.radio-canada.ca/mordu/recettes/7899/poitrines-poulet-sauce-creme-champignons
INSERT INTO aliment_recette VALUES (93, 15);
INSERT INTO aliment_recette VALUES (33, 15);
INSERT INTO aliment_recette VALUES (18, 15);
INSERT INTO aliment_recette VALUES (142, 15);
INSERT INTO aliment_recette VALUES (139, 15);
INSERT INTO aliment_recette VALUES (17, 15);
INSERT INTO aliment_recette VALUES (143, 15);
INSERT INTO aliment_recette VALUES (4, 15);
INSERT INTO aliment_recette VALUES (159, 15);
INSERT INTO aliment_recette VALUES (37, 15);
INSERT INTO aliment_recette VALUES (87, 15);
INSERT INTO aliment_recette VALUES (103, 15);
INSERT INTO aliment_recette VALUES (145, 15);

-- https://www.5ingredients15minutes.com/fr/recettes/plats-principaux/poulet/cuisses-de-poulet-roties-au-four/
INSERT INTO aliment_recette VALUES (93, 16);
INSERT INTO aliment_recette VALUES (18, 16);
INSERT INTO aliment_recette VALUES (6, 16);
INSERT INTO aliment_recette VALUES (139, 16);
INSERT INTO aliment_recette VALUES (132, 16);

-- https://www.joseedistasio.ca/recettes/batonnets-de-poisson-croustillants-sans-friture/
INSERT INTO aliment_recette VALUES (100, 17);
INSERT INTO aliment_recette VALUES (31, 17);
INSERT INTO aliment_recette VALUES (101, 17);
INSERT INTO aliment_recette VALUES (24, 17);
INSERT INTO aliment_recette VALUES (18, 17);
INSERT INTO aliment_recette VALUES (19, 17);
INSERT INTO aliment_recette VALUES (132, 17);
INSERT INTO aliment_recette VALUES (87, 17);

-- https://madame.lefigaro.fr/recettes/pates-tomate-060201-200395
INSERT INTO aliment_recette VALUES (105, 18);
INSERT INTO aliment_recette VALUES (90, 18);
INSERT INTO aliment_recette VALUES (132, 18);
INSERT INTO aliment_recette VALUES (18, 18);
INSERT INTO aliment_recette VALUES (19, 18);
INSERT INTO aliment_recette VALUES (68, 18);
INSERT INTO aliment_recette VALUES (37, 18);

-- https://www.joseedistasio.ca/recettes/entrees-accompagnements/gravlax-de-saumon/
INSERT INTO aliment_recette VALUES (56, 19);
INSERT INTO aliment_recette VALUES (18, 19);
INSERT INTO aliment_recette VALUES (83, 19);
INSERT INTO aliment_recette VALUES (60, 19);

-- https://ricardocuisine.com/recettes/234-crepes-americaines-aux-bleuets-pancakes-aux-bleuets
INSERT INTO aliment_recette VALUES (24, 20);
INSERT INTO aliment_recette VALUES (59, 20);
INSERT INTO aliment_recette VALUES (72, 20);
INSERT INTO aliment_recette VALUES (57, 20);
INSERT INTO aliment_recette VALUES (66, 20);
INSERT INTO aliment_recette VALUES (61, 20);
INSERT INTO aliment_recette VALUES (2, 20);

-- https://www.ricardocuisine.com/recettes/6082-boeuf-braise-au-vin-rouge
INSERT INTO aliment_recette VALUES (112, 21);
INSERT INTO aliment_recette VALUES (4, 21);
INSERT INTO aliment_recette VALUES (132, 21);
INSERT INTO aliment_recette VALUES (19, 21);
INSERT INTO aliment_recette VALUES (98, 21);
INSERT INTO aliment_recette VALUES (24, 21);
INSERT INTO aliment_recette VALUES (160, 21);
INSERT INTO aliment_recette VALUES (42, 21);
INSERT INTO aliment_recette VALUES (85, 21);
INSERT INTO aliment_recette VALUES (21, 21);
INSERT INTO aliment_recette VALUES (95, 21);
INSERT INTO aliment_recette VALUES (161, 21);

-- https://www.metro.ca/recettes-et-occasions/recettes/ratatouille-grillee-en-salade
INSERT INTO aliment_recette VALUES (131, 23);
INSERT INTO aliment_recette VALUES (74, 23);
INSERT INTO aliment_recette VALUES (75, 23);
INSERT INTO aliment_recette VALUES (10, 23);
INSERT INTO aliment_recette VALUES (4, 23);
INSERT INTO aliment_recette VALUES (90, 23);
INSERT INTO aliment_recette VALUES (37, 23);
INSERT INTO aliment_recette VALUES (18, 23);
INSERT INTO aliment_recette VALUES (19, 23);
INSERT INTO aliment_recette VALUES (67, 23);
INSERT INTO aliment_recette VALUES (68, 23);
INSERT INTO aliment_recette VALUES (69, 23);
INSERT INTO aliment_recette VALUES (77, 23);
INSERT INTO aliment_recette VALUES (132, 23);
INSERT INTO aliment_recette VALUES (114, 23);

-- https://www.boblechef.com/recettes/tartare-de-thon-classique
INSERT INTO aliment_recette VALUES (118, 24);
INSERT INTO aliment_recette VALUES (67, 24);
INSERT INTO aliment_recette VALUES (77, 24);
INSERT INTO aliment_recette VALUES (120, 24);
INSERT INTO aliment_recette VALUES (132, 24);
INSERT INTO aliment_recette VALUES (87, 24);
INSERT INTO aliment_recette VALUES (144, 24);
INSERT INTO aliment_recette VALUES (72, 24);

-- https://www.ricardocuisine.com/recettes/9583-chaudree-de-pommes-de-terre-sans-produits-laitiers
INSERT INTO aliment_recette VALUES (0, 26);
INSERT INTO aliment_recette VALUES (4, 26);
INSERT INTO aliment_recette VALUES (122, 26);
INSERT INTO aliment_recette VALUES (18, 26);
INSERT INTO aliment_recette VALUES (19, 26);
INSERT INTO aliment_recette VALUES (143, 26);
INSERT INTO aliment_recette VALUES (137, 26);
INSERT INTO aliment_recette VALUES (144, 26);
INSERT INTO aliment_recette VALUES (145, 26);
INSERT INTO aliment_recette VALUES (121, 26);
INSERT INTO aliment_recette VALUES (22, 26);
INSERT INTO aliment_recette VALUES (37, 26);
INSERT INTO aliment_recette VALUES (24, 26);

-- https://www.ricardocuisine.com/recettes/10009-nouilles-asiatiques-au-porc-de-style-dan-dan 
INSERT INTO aliment_recette VALUES (11, 28);
INSERT INTO aliment_recette VALUES (129, 28);
INSERT INTO aliment_recette VALUES (50, 28);
INSERT INTO aliment_recette VALUES (51, 28);
INSERT INTO aliment_recette VALUES (49, 28);
INSERT INTO aliment_recette VALUES (67, 28);
INSERT INTO aliment_recette VALUES (58, 28);
INSERT INTO aliment_recette VALUES (146, 28);
INSERT INTO aliment_recette VALUES (147, 28);
INSERT INTO aliment_recette VALUES (148, 28);
INSERT INTO aliment_recette VALUES (142, 28);
INSERT INTO aliment_recette VALUES (37, 28);
INSERT INTO aliment_recette VALUES (83, 28);
INSERT INTO aliment_recette VALUES (162, 28);
INSERT INTO aliment_recette VALUES (17, 28);
INSERT INTO aliment_recette VALUES (45, 28);
INSERT INTO aliment_recette VALUES (128, 28);
INSERT INTO aliment_recette VALUES (130, 28);

-- https://www.ricardocuisine.com/recettes/9027-pate-mexicain
INSERT INTO aliment_recette VALUES (3, 29);
INSERT INTO aliment_recette VALUES (4, 29);
INSERT INTO aliment_recette VALUES (9, 29);
INSERT INTO aliment_recette VALUES (35, 29);
INSERT INTO aliment_recette VALUES (34, 29);
INSERT INTO aliment_recette VALUES (38, 29);
INSERT INTO aliment_recette VALUES (18, 29);
INSERT INTO aliment_recette VALUES (19, 29);
INSERT INTO aliment_recette VALUES (135, 29);
INSERT INTO aliment_recette VALUES (149, 29);
INSERT INTO aliment_recette VALUES (150, 29);
INSERT INTO aliment_recette VALUES (151, 29);
INSERT INTO aliment_recette VALUES (24, 29);
INSERT INTO aliment_recette VALUES (1, 29);
INSERT INTO aliment_recette VALUES (125, 29);
INSERT INTO aliment_recette VALUES (22, 29);
INSERT INTO aliment_recette VALUES (90, 29);
INSERT INTO aliment_recette VALUES (87, 29);

-- https://www.ricardocuisine.com/recettes/214-tacos-au-poulet
INSERT INTO aliment_recette VALUES (93, 30);
INSERT INTO aliment_recette VALUES (156, 30);
INSERT INTO aliment_recette VALUES (32, 30);
INSERT INTO aliment_recette VALUES (41, 30);
INSERT INTO aliment_recette VALUES (124, 30);
INSERT INTO aliment_recette VALUES (135, 30);
INSERT INTO aliment_recette VALUES (152, 30);
INSERT INTO aliment_recette VALUES (134, 30);
INSERT INTO aliment_recette VALUES (153, 30);
INSERT INTO aliment_recette VALUES (4, 30);
INSERT INTO aliment_recette VALUES (37, 30);
INSERT INTO aliment_recette VALUES (132, 30);
INSERT INTO aliment_recette VALUES (82, 30);
INSERT INTO aliment_recette VALUES (103, 30);
INSERT INTO aliment_recette VALUES (91, 30);
INSERT INTO aliment_recette VALUES (84, 30);
INSERT INTO aliment_recette VALUES (123, 30);

-- https://ricardocuisine.com/recettes/6985-keftas-de-boeuf-sur-pain-naan
INSERT INTO aliment_recette VALUES (3, 31);
INSERT INTO aliment_recette VALUES (67, 31);
INSERT INTO aliment_recette VALUES (74, 31);
INSERT INTO aliment_recette VALUES (32, 31);
INSERT INTO aliment_recette VALUES (76, 31);
INSERT INTO aliment_recette VALUES (18, 31);
INSERT INTO aliment_recette VALUES (19, 31);
INSERT INTO aliment_recette VALUES (27, 31);
INSERT INTO aliment_recette VALUES (131, 31);
INSERT INTO aliment_recette VALUES (132, 31);
INSERT INTO aliment_recette VALUES (133, 31);
INSERT INTO aliment_recette VALUES (36, 31);
INSERT INTO aliment_recette VALUES (125, 31);
INSERT INTO aliment_recette VALUES (6, 31);

-- https://www.ricardocuisine.com/recettes/7863-ragout-d-aubergine-a-la-viande
INSERT INTO aliment_recette VALUES (3, 32);
INSERT INTO aliment_recette VALUES (74, 32);
INSERT INTO aliment_recette VALUES (75, 32);
INSERT INTO aliment_recette VALUES (10, 32);
INSERT INTO aliment_recette VALUES (4, 32);
INSERT INTO aliment_recette VALUES (37, 32);
INSERT INTO aliment_recette VALUES (132, 32);
INSERT INTO aliment_recette VALUES (18, 32);
INSERT INTO aliment_recette VALUES (19, 32);
INSERT INTO aliment_recette VALUES (40, 32);
INSERT INTO aliment_recette VALUES (154, 32);
INSERT INTO aliment_recette VALUES (46, 32);
INSERT INTO aliment_recette VALUES (116, 32);
INSERT INTO aliment_recette VALUES (82, 32);
INSERT INTO aliment_recette VALUES (125, 32);

-- Ajout des diètes

INSERT INTO diete VALUES (0, 'Omnivore');
INSERT INTO diete VALUES (1, 'Végétarienne');
INSERT INTO diete VALUES (2, 'Végétalienne');
INSERT INTO diete VALUES (3, 'Paléo');
INSERT INTO diete VALUES (4, 'Pesco-végétarienne');
INSERT INTO diete VALUES (5, 'Ovo-lacto-végétarienne');
INSERT INTO diete VALUES (6, 'Lacto-végétarisme');

-- Ajout des diètes avec les recettes

INSERT INTO recette_diete VALUES (0, 0);
INSERT INTO recette_diete VALUES (1, 0);
INSERT INTO recette_diete VALUES (1, 1);
INSERT INTO recette_diete VALUES (1, 4);
INSERT INTO recette_diete VALUES (1, 5);
INSERT INTO recette_diete VALUES (1, 6);
INSERT INTO recette_diete VALUES (2, 0);
INSERT INTO recette_diete VALUES (3, 0);
INSERT INTO recette_diete VALUES (3, 1);
INSERT INTO recette_diete VALUES (3, 4);
INSERT INTO recette_diete VALUES (3, 5);
INSERT INTO recette_diete VALUES (3, 6);
INSERT INTO recette_diete VALUES (4, 0);
INSERT INTO recette_diete VALUES (5, 0);
INSERT INTO recette_diete VALUES (5, 4);
INSERT INTO recette_diete VALUES (6, 0);
INSERT INTO recette_diete VALUES (7, 0);
INSERT INTO recette_diete VALUES (7, 1);
INSERT INTO recette_diete VALUES (7, 2);
INSERT INTO recette_diete VALUES (7, 3);
INSERT INTO recette_diete VALUES (7, 4);
INSERT INTO recette_diete VALUES (7, 5);
INSERT INTO recette_diete VALUES (7, 6);
INSERT INTO recette_diete VALUES (8, 0);
INSERT INTO recette_diete VALUES (8, 1);
INSERT INTO recette_diete VALUES (8, 2);
INSERT INTO recette_diete VALUES (9, 0);
INSERT INTO recette_diete VALUES (9, 1);
INSERT INTO recette_diete VALUES (9, 2);
INSERT INTO recette_diete VALUES (9, 3);
INSERT INTO recette_diete VALUES (9, 4);
INSERT INTO recette_diete VALUES (9, 5);
INSERT INTO recette_diete VALUES (9, 6);
INSERT INTO recette_diete VALUES (10, 0);
INSERT INTO recette_diete VALUES (10, 1);
INSERT INTO recette_diete VALUES (10, 4);
INSERT INTO recette_diete VALUES (10, 5);
INSERT INTO recette_diete VALUES (10, 6);
INSERT INTO recette_diete VALUES (11, 0);
INSERT INTO recette_diete VALUES (11, 1);
INSERT INTO recette_diete VALUES (11, 4);
INSERT INTO recette_diete VALUES (11, 5);
INSERT INTO recette_diete VALUES (12, 0);
INSERT INTO recette_diete VALUES (12, 1);
INSERT INTO recette_diete VALUES (12, 2);
INSERT INTO recette_diete VALUES (12, 4);
INSERT INTO recette_diete VALUES (12, 5);
INSERT INTO recette_diete VALUES (12, 6);
INSERT INTO recette_diete VALUES (13, 0);
INSERT INTO recette_diete VALUES (13, 1);
INSERT INTO recette_diete VALUES (13, 2);
INSERT INTO recette_diete VALUES (13, 4);
INSERT INTO recette_diete VALUES (13, 5);
INSERT INTO recette_diete VALUES (13, 6);
INSERT INTO recette_diete VALUES (14, 0);
INSERT INTO recette_diete VALUES (15, 0);
INSERT INTO recette_diete VALUES (15, 3);
INSERT INTO recette_diete VALUES (16, 0);
INSERT INTO recette_diete VALUES (16, 3);
INSERT INTO recette_diete VALUES (17, 0);
INSERT INTO recette_diete VALUES (17, 4);
INSERT INTO recette_diete VALUES (18, 0);
INSERT INTO recette_diete VALUES (18, 1);
INSERT INTO recette_diete VALUES (18, 2);
INSERT INTO recette_diete VALUES (18, 4);
INSERT INTO recette_diete VALUES (18, 5);
INSERT INTO recette_diete VALUES (19, 0);
INSERT INTO recette_diete VALUES (19, 3);
INSERT INTO recette_diete VALUES (19, 4);
INSERT INTO recette_diete VALUES (20, 0);
INSERT INTO recette_diete VALUES (20, 1);
INSERT INTO recette_diete VALUES (20, 2);
INSERT INTO recette_diete VALUES (20, 4);
INSERT INTO recette_diete VALUES (20, 5);
INSERT INTO recette_diete VALUES (20, 6);
INSERT INTO recette_diete VALUES (21, 0);
INSERT INTO recette_diete VALUES (21, 3);
INSERT INTO recette_diete VALUES (22, 0);
INSERT INTO recette_diete VALUES (23, 0);
INSERT INTO recette_diete VALUES (23, 1);
INSERT INTO recette_diete VALUES (23, 2);
INSERT INTO recette_diete VALUES (23, 3);
INSERT INTO recette_diete VALUES (23, 4);
INSERT INTO recette_diete VALUES (23, 5);
INSERT INTO recette_diete VALUES (23, 6);
INSERT INTO recette_diete VALUES (24, 0);
INSERT INTO recette_diete VALUES (24, 3);
INSERT INTO recette_diete VALUES (24, 4);
INSERT INTO recette_diete VALUES (26, 0);
INSERT INTO recette_diete VALUES (26, 1);
INSERT INTO recette_diete VALUES (26, 2);
INSERT INTO recette_diete VALUES (26, 4);
INSERT INTO recette_diete VALUES (26, 5);
INSERT INTO recette_diete VALUES (26, 6);
INSERT INTO recette_diete VALUES (27, 0);
INSERT INTO recette_diete VALUES (27, 1);
INSERT INTO recette_diete VALUES (27, 3);
INSERT INTO recette_diete VALUES (27, 4);
INSERT INTO recette_diete VALUES (27, 5);
INSERT INTO recette_diete VALUES (27, 6);
INSERT INTO recette_diete VALUES (28, 0);
INSERT INTO recette_diete VALUES (29, 0);
INSERT INTO recette_diete VALUES (30, 0);
INSERT INTO recette_diete VALUES (31, 0);
INSERT INTO recette_diete VALUES (32, 3);
INSERT INTO recette_diete VALUES (32, 0);


-- Ajout des Allergies

INSERT INTO Allergie VALUES (0,'Arachide');
INSERT INTO Allergie VALUES (1,'Lactose');
INSERT INTO Allergie VALUES (2,'Gluten');
INSERT INTO Allergie VALUES (3,'Poisson');
INSERT INTO Allergie VALUES (4,'Fruit de mer');
INSERT INTO Allergie VALUES (5,'Oeuf');
INSERT INTO Allergie VALUES (6,'Soja');
INSERT INTO Allergie VALUES (7,'Sesame');

-- Ajout epicerie

INSERT INTO epicerie VALUES (0, 'Super D');
INSERT INTO epicerie VALUES (1, 'IGD');
INSERT INTO epicerie VALUES (2, 'Detro');

-- Ajout des aliements avec les epiceries

INSERT INTO aliment_epicerie VALUES (0, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (0, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (0, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (1, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (1, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (2, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (3, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (3, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (4, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (5, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (5, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (5, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (6, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (6, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (7, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (7, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (8, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (9, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (9, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (10, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (10, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (11, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (12, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (13, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (13, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (14, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (14, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (15, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (16, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (16, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (16, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (17, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (17, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (18, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (18, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (18, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (19, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (19, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (20, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (21, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (22, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (23, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (23, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (23, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (24, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (25, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (25, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (26, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (27, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (27, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (28, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (29, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (29, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (30, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (31, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (31, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (32, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (32, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (32, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (33, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (33, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (34, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (34, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (35, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (35, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (35, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (36, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (36, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (37, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (37, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (38, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (38, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (38, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (39, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (39, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (39, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (40, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (40, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (40, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (41, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (41, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (42, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (42, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (43, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (43, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (44, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (45, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (45, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (46, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (47, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (48, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (49, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (50, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (51, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (51, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (52, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (52, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (53, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (53, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (54, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (54, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (54, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (55, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (55, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (56, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (57, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (58, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (59, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (60, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (61, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (61, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (62, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (63, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (64, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (65, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (66, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (67, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (68, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (68, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (69, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (69, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (70, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (71, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (72, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (73, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (74, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (74, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (75, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (76, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (77, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (77, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (78, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (79, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (80, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (80, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (80, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (81, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (82, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (83, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (84, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (84, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (85, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (86, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (87, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (88, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (89, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (90, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (91, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (92, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (93, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (93, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (94, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (95, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (96, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (97, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (98, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (99, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (100, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (101, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (101, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (102, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (102, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (103, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (103, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (104, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (104, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (105, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (106, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (107, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (108, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (109, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (110, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (111, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (111, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (111, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (112, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (112, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (113, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (113, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (114, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (115, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (116, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (116, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (117, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (118, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (119, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (120, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (121, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (122, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (123, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (123, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (124, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (124, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (124, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (125, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (126, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (127, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (127, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (128, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (128, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (129, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (130, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (131, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (131, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (131, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (132, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (132, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (132, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (133, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (133, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (133, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (134, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (134, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (134, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (135, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (135, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (136, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (136, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (137, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (138, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (138, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (138, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (139, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (139, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (139, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (140, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (140, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (140, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (141, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (141, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (142, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (142, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (142, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (143, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (143, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (143, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (144, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (144, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (144, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (145, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (145, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (145, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (146, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (146, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (146, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (147, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (147, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (147, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (148, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (148, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (149, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (149, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (150, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (150, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (150, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (151, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (151, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (151, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (152, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (152, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (152, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (153, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (153, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (153, 2, 0.00);
INSERT INTO aliment_epicerie VALUES (154, 0, 0.00);
INSERT INTO aliment_epicerie VALUES (154, 1, 0.00);
INSERT INTO aliment_epicerie VALUES (154, 2, 0.00);

-- Ajout aliments et allergies

INSERT INTO Aliment_Allergie VALUES (1, 1);  
INSERT INTO Aliment_Allergie VALUES (2, 1);  
INSERT INTO Aliment_Allergie VALUES (8, 4);
INSERT INTO Aliment_Allergie VALUES (12,2);
INSERT INTO Aliment_Allergie VALUES (12,6);
INSERT INTO Aliment_Allergie VALUES (10,2);
INSERT INTO Aliment_Allergie VALUES (23,1);
INSERT INTO Aliment_Allergie VALUES (24, 2);
INSERT INTO Aliment_Allergie VALUES (26, 2);
INSERT INTO Aliment_Allergie VALUES (27, 1);
INSERT INTO Aliment_Allergie VALUES (28, 1);
INSERT INTO Aliment_Allergie VALUES (50, 6);
INSERT INTO Aliment_Allergie VALUES (52, 6); 
INSERT INTO Aliment_Allergie VALUES (56, 3); 
INSERT INTO Aliment_Allergie VALUES (58, 7);
INSERT INTO Aliment_Allergie VALUES (62, 6);
INSERT INTO Aliment_Allergie VALUES (65, 2);
INSERT INTO Aliment_Allergie VALUES (72, 5);
INSERT INTO Aliment_Allergie VALUES (86, 5);
INSERT INTO Aliment_Allergie VALUES (89, 2);
INSERT INTO Aliment_Allergie VALUES (91, 1);
INSERT INTO Aliment_Allergie VALUES (96, 6);
INSERT INTO Aliment_Allergie VALUES (99, 1);
INSERT INTO Aliment_Allergie VALUES (100, 3);
INSERT INTO Aliment_Allergie VALUES (105, 2);
INSERT INTO Aliment_Allergie VALUES (106, 2);
INSERT INTO Aliment_Allergie VALUES (107, 1);
INSERT INTO Aliment_Allergie VALUES (118, 3);
INSERT INTO Aliment_Allergie VALUES (124, 1);
INSERT INTO Aliment_Allergie VALUES (125, 1);
INSERT INTO Aliment_Allergie VALUES (127, 7);
INSERT INTO Aliment_Allergie VALUES (130, 0);
INSERT INTO Aliment_Allergie VALUES (133, 2);
INSERT INTO Aliment_Allergie VALUES (138, 7); 
INSERT INTO Aliment_Allergie VALUES (146, 0);  
INSERT INTO Aliment_Allergie VALUES (151, 1);  
INSERT INTO Aliment_Allergie VALUES (152, 2);  
INSERT INTO Aliment_Allergie VALUES (159, 1);  

--Ajout de compte

INSERT INTO client (courriel, password) VALUES ("admin", "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918");

--Ajout des allergies pour un client

INSERT INTO client_allergie VALUES (1, 2);
INSERT INTO client_allergie VALUES (1, 3);

--Ajout d'une diete pour un client

INSERT INTO client_diete VALUES (1, 1);
