--Ajout des recettes dans la BD

INSERT INTO recette VALUES (0, 'Pâté chinois', 0);
INSERT INTO recette VALUES (1, 'Pâté chinois végétarien', 0);
INSERT INTO recette VALUES (2, 'Spaghetti', 0);
INSERT INTO recette VALUES (3, 'Pizza trois fromages', 0);
INSERT INTO recette VALUES (4, 'Pizza pepperoni fromage', 0);
INSERT INTO recette VALUES (5, 'Tacos crevettes', 0);
INSERT INTO recette VALUES (6, 'Chili au boeuf', 0);
INSERT INTO recette VALUES (7, 'Lentille dahl', 0);
INSERT INTO recette VALUES (8, 'Tofu gochujang', 0);
INSERT INTO recette VALUES (9, 'Mijoté de pois chiche', 0);
INSERT INTO recette VALUES (10, 'Orzo aux tomates grillées  et féta', 0);
INSERT INTO recette VALUES (11, 'Pain aux bananes', 0);
INSERT INTO recette VALUES (12, 'Tajine de légumes', 0);
INSERT INTO recette VALUES (13, 'Tofu piri piri', 0);
INSERT INTO recette VALUES (14, 'Hamburger', 0);
INSERT INTO recette VALUES (15, 'Sauce au poulet et aux champignons', 0);
INSERT INTO recette VALUES (16, 'Cuisses de poulets rôties', 0);
INSERT INTO recette VALUES (17, 'Bâtonnes de poisson croustillants sans friture', 0);
INSERT INTO recette VALUES (18, 'Pâtes à la sauce tomate', 0);
INSERT INTO recette VALUES (19, 'Gravlax de saumon', 0);
INSERT INTO recette VALUES (20, 'Crêpes multigrains aux bleuets', 0);
INSERT INTO recette VALUES (21, 'Boeuf braisé', 0);
INSERT INTO recette VALUES (22, 'Tajine de poulet au citron confit', 0);
INSERT INTO recette VALUES (23, 'Ratatouille grilée en salade', 0);
INSERT INTO recette VALUES (24, 'Tartare de thon', 0);
INSERT INTO recette VALUES (26, 'Chaudrée de pommes de terre sans produits laitiers', 0);
INSERT INTO recette VALUES (27, 'Palak paneer', 0);
INSERT INTO recette VALUES (28, 'Nouilles asatiques au porc', 0);
INSERT INTO recette VALUES (29, 'Pâté mexicain', 0);
INSERT INTO recette VALUES (30, 'Tacos au poulet', 0);
INSERT INTO recette VALUES (31, 'Keftas de boeufs sur pain naan', 0);
INSERT INTO recette VALUES (32, "Ragoût d'aubergine à la viande", 0);

--Ajout des ingrédients dans la BD

INSERT INTO aliment VALUES (0, 'Pomme de terre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (1, 'Beurre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (2, 'Lait', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (3, 'Boeuf haché', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (4, 'Oignon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (5, 'Maïs en crème', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (6, 'Paprika', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (7, 'Persil séché', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (8, 'Crevette', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (9, 'Patate douce', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (10, 'Poivron rouge', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (11, 'Porc haché', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (12, 'Viande haché végétarienne', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (13, 'Pois chiche', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (14, 'Pâte de tomate', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (15, 'Épinards', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (16, 'Cari', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (17, 'Huile de canola', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (18, 'Sel', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (19, 'Poivre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (20, 'Spaghetti', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (21, 'Carotte', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (22, 'Celeri', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (23, 'Mozzarella', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (24, 'Farine', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (25, 'Sauce à pizza', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (26, 'Pâte à pizza', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (27, 'Ricotta', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (28, 'Féta', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (29, 'Pepperoni', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (30, 'Tortilla', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (31, 'Mangue', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (32, 'Coriandre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (33, 'Champignon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (34, 'Poudre de chili', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (35, 'Haricot rouge', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (36, 'Cumin', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (37, 'Ail', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (38, 'Piment jalapeno', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (39, 'Café', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (40, 'Tomates en dés', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (41, 'Jus de lime', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (42, 'Bouillon de boeuf', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (43, 'Lentille rouge', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (44, 'Huile de noix de coco', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (45, 'Gingembre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (46, 'Garam masala', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (47, 'Bouillon végétarien', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (48, 'Lait de coco', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (49, 'Goghujang', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (50, 'Sauce soya', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (51, 'Vinaigre de riz', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (52, 'Tofu', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (53, 'Fécule de maïs', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (54, 'Broccoli', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (55, 'Pois chiche', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (56, 'Saumon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (57, 'Bleuet', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (58, 'Graine de sésame', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (59, 'Poudre à pâte', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (60, 'Cassonade', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (61, 'Extrait de vanille', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (62, 'Boisson de soya', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (63, 'Flocon davoine', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (64, 'Sambal Oelek', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (65, 'Orzo', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (66, 'Sirop dérable', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (67, 'Échalote', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (68, 'Basilic', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (69, 'Vinaigre de vin rouge', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (70, 'Banane', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (71, 'Bicarbonate de soude', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (72, 'Oeuf', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (73, 'Rutabaga', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (74, 'Aubergine', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (75, 'Courgette', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (76, 'Pâte harissa', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (77, 'Citron', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (78, 'Olive verte', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (79, 'Abricots séchés', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (80, 'Vinaigre de vin blanc', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (81, 'Ail en poudre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (82, 'Origan', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (83, 'Sucre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (84, 'Laitue', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (85, 'Ketchup', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (86, 'Mayonnaise', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (87, 'Moutarde', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (88, 'Cornichon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (89, 'Pain hamburger', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (90, 'Tomate', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (91, 'Cheddar', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (92, 'Champignon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (93, 'Poulet', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (94, 'Dinde', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (95, 'Pancetta', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (96, 'Lait', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (97, 'Sauge fraîche', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (98, 'Muscade', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (99, 'Parmesan', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (100, 'Aiglefin', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (101, 'Chapelure', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (102, 'Cannelle', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (103, 'Persil', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (104, 'Olive noire', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (105, 'Penne', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (106, 'Rigatoni', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (107, 'Pecorino', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (108, 'Clou de girofle', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (109, 'Menthe', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (110, 'Graine de coriandre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (111, 'Orange', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (112, 'Rôti de palette de boeuf', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (113, 'Bacon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (114, 'Vinaigne balsamique', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (115, 'Romarin', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (116, 'Flocon de piment fort', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (117, 'Tomate cerise', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (118, 'Thon', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (119, 'Limes', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (120, 'Câpre', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (121, 'Poireau', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (122, 'Maïs', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (123, 'Sauce tabasco', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (124, 'Crème sure', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (125, 'Yogourt', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (126, 'Échalot française', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (127, 'Pâte de sésame', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (128, 'Sauce hoisin', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (129, 'Nouille ramen', 0.00, 'Type', 'Épicerie');
INSERT INTO aliment VALUES (130, 'Arachide', 0.00, 'Type', 'Épicerie');

--Ajout des recettes avec les aliments

INSERT INTO aliment_recette VALUES (0, 1);
INSERT INTO aliment_recette VALUES (1, 1);
INSERT INTO aliment_recette VALUES (2, 1);
INSERT INTO aliment_recette VALUES (12, 1);
INSERT INTO aliment_recette VALUES (4, 1);
INSERT INTO aliment_recette VALUES (5, 1);
INSERT INTO aliment_recette VALUES (6, 1);
INSERT INTO aliment_recette VALUES (7, 1);

INSERT INTO aliment_recette VALUES (3, 2);
INSERT INTO aliment_recette VALUES (4, 2);
INSERT INTO aliment_recette VALUES (21, 2);
INSERT INTO aliment_recette VALUES (22, 2);
INSERT INTO aliment_recette VALUES (14, 2);
INSERT INTO aliment_recette VALUES (18, 2);
INSERT INTO aliment_recette VALUES (19, 2);
INSERT INTO aliment_recette VALUES (25, 3);
INSERT INTO aliment_recette VALUES (26, 3);
INSERT INTO aliment_recette VALUES (23, 3);
INSERT INTO aliment_recette VALUES (27, 3);
INSERT INTO aliment_recette VALUES (28, 3);
INSERT INTO aliment_recette VALUES (25, 4);
INSERT INTO aliment_recette VALUES (26, 4);
INSERT INTO aliment_recette VALUES (23, 4);
INSERT INTO aliment_recette VALUES (29, 4);
INSERT INTO aliment_recette VALUES (30, 5);
INSERT INTO aliment_recette VALUES (8, 5);
INSERT INTO aliment_recette VALUES (31, 5);
INSERT INTO aliment_recette VALUES (32, 5);
INSERT INTO aliment_recette VALUES (41, 5);
INSERT INTO aliment_recette VALUES (3, 6);
INSERT INTO aliment_recette VALUES (4, 6);
INSERT INTO aliment_recette VALUES (21, 6);
INSERT INTO aliment_recette VALUES (14, 6);
INSERT INTO aliment_recette VALUES (33, 6);
INSERT INTO aliment_recette VALUES (34, 6);
INSERT INTO aliment_recette VALUES (35, 6);
INSERT INTO aliment_recette VALUES (36, 6);
INSERT INTO aliment_recette VALUES (37, 6);
INSERT INTO aliment_recette VALUES (38, 6);
INSERT INTO aliment_recette VALUES (40, 6);
INSERT INTO aliment_recette VALUES (42, 6);
INSERT INTO aliment_recette VALUES (43, 7);
INSERT INTO aliment_recette VALUES (21, 7);
INSERT INTO aliment_recette VALUES (15, 7);
INSERT INTO aliment_recette VALUES (16, 7);
INSERT INTO aliment_recette VALUES (44, 7);
INSERT INTO aliment_recette VALUES (45, 7);
INSERT INTO aliment_recette VALUES (46, 7);
INSERT INTO aliment_recette VALUES (47, 7);
INSERT INTO aliment_recette VALUES (48, 7);
INSERT INTO aliment_recette VALUES (18, 7);
INSERT INTO aliment_recette VALUES (52, 8);
INSERT INTO aliment_recette VALUES (49, 8);
INSERT INTO aliment_recette VALUES (50, 8);
INSERT INTO aliment_recette VALUES (51, 8);
INSERT INTO aliment_recette VALUES (17, 8);
INSERT INTO aliment_recette VALUES (54, 8);
INSERT INTO aliment_recette VALUES (53, 8);
INSERT INTO aliment_recette VALUES (18, 8);
INSERT INTO aliment_recette VALUES (13, 9);
INSERT INTO aliment_recette VALUES (21, 9);
INSERT INTO aliment_recette VALUES (4, 9);
INSERT INTO aliment_recette VALUES (37, 9);
INSERT INTO aliment_recette VALUES (40, 9);
INSERT INTO aliment_recette VALUES (42, 9);
INSERT INTO aliment_recette VALUES (19, 9);
INSERT INTO aliment_recette VALUES (65, 10);
INSERT INTO aliment_recette VALUES (67, 10);
INSERT INTO aliment_recette VALUES (68, 10);
INSERT INTO aliment_recette VALUES (28, 10);
INSERT INTO aliment_recette VALUES (17, 10);
INSERT INTO aliment_recette VALUES (1, 11);
INSERT INTO aliment_recette VALUES (70, 11);
INSERT INTO aliment_recette VALUES (60, 11);
INSERT INTO aliment_recette VALUES (61, 11);
INSERT INTO aliment_recette VALUES (24, 11);
INSERT INTO aliment_recette VALUES (71, 11);
INSERT INTO aliment_recette VALUES (72, 11);
INSERT INTO aliment_recette VALUES (21, 12);
INSERT INTO aliment_recette VALUES (74, 12);
INSERT INTO aliment_recette VALUES (75, 12);
INSERT INTO aliment_recette VALUES (79, 12);
INSERT INTO aliment_recette VALUES (77, 12);
INSERT INTO aliment_recette VALUES (78, 12);
INSERT INTO aliment_recette VALUES (76, 12);
INSERT INTO aliment_recette VALUES (14, 12);
INSERT INTO aliment_recette VALUES (52, 13);
INSERT INTO aliment_recette VALUES (64, 13);
INSERT INTO aliment_recette VALUES (51, 13);
INSERT INTO aliment_recette VALUES (53, 13);
INSERT INTO aliment_recette VALUES (18, 13);
INSERT INTO aliment_recette VALUES (3, 14);
INSERT INTO aliment_recette VALUES (84, 14);
INSERT INTO aliment_recette VALUES (85, 14);
INSERT INTO aliment_recette VALUES (86, 14);
INSERT INTO aliment_recette VALUES (87, 14);
INSERT INTO aliment_recette VALUES (88, 14);
INSERT INTO aliment_recette VALUES (89, 14);
INSERT INTO aliment_recette VALUES (90, 14);
INSERT INTO aliment_recette VALUES (91, 14);
INSERT INTO aliment_recette VALUES (93, 15);
INSERT INTO aliment_recette VALUES (33, 15);
INSERT INTO aliment_recette VALUES (24, 15);
INSERT INTO aliment_recette VALUES (2, 15);
INSERT INTO aliment_recette VALUES (96, 15);
INSERT INTO aliment_recette VALUES (97, 15);
INSERT INTO aliment_recette VALUES (98, 15);
INSERT INTO aliment_recette VALUES (99, 15);
INSERT INTO aliment_recette VALUES (18, 15);
INSERT INTO aliment_recette VALUES (93, 16);
INSERT INTO aliment_recette VALUES (18, 16);
INSERT INTO aliment_recette VALUES (19, 16);
INSERT INTO aliment_recette VALUES (100, 16);
INSERT INTO aliment_recette VALUES (103, 16);
INSERT INTO aliment_recette VALUES (100, 17);
INSERT INTO aliment_recette VALUES (2, 17);
INSERT INTO aliment_recette VALUES (101, 17);
INSERT INTO aliment_recette VALUES (24, 17);
INSERT INTO aliment_recette VALUES (18, 17);
INSERT INTO aliment_recette VALUES (19, 17);
INSERT INTO aliment_recette VALUES (105, 18);
INSERT INTO aliment_recette VALUES (14, 18);
INSERT INTO aliment_recette VALUES (104, 18);
INSERT INTO aliment_recette VALUES (17, 18);
INSERT INTO aliment_recette VALUES (18, 18);
INSERT INTO aliment_recette VALUES (19, 18);
INSERT INTO aliment_recette VALUES (56, 19);
INSERT INTO aliment_recette VALUES (18, 19);
INSERT INTO aliment_recette VALUES (83, 19);
INSERT INTO aliment_recette VALUES (58, 19);
INSERT INTO aliment_recette VALUES (119, 19);
INSERT INTO aliment_recette VALUES (24, 20);
INSERT INTO aliment_recette VALUES (59, 20);
INSERT INTO aliment_recette VALUES (63, 20);
INSERT INTO aliment_recette VALUES (62, 20);
INSERT INTO aliment_recette VALUES (72, 20);
INSERT INTO aliment_recette VALUES (57, 20);
INSERT INTO aliment_recette VALUES (66, 20);
INSERT INTO aliment_recette VALUES (61, 20);
INSERT INTO aliment_recette VALUES (3, 21);
INSERT INTO aliment_recette VALUES (112, 21);
INSERT INTO aliment_recette VALUES (4, 21);
INSERT INTO aliment_recette VALUES (113, 21);
INSERT INTO aliment_recette VALUES (115, 21);
INSERT INTO aliment_recette VALUES (39, 21);
INSERT INTO aliment_recette VALUES (114, 21);
INSERT INTO aliment_recette VALUES (93, 22);
INSERT INTO aliment_recette VALUES (73, 22);
INSERT INTO aliment_recette VALUES (77, 22);
INSERT INTO aliment_recette VALUES (78, 22);
INSERT INTO aliment_recette VALUES (79, 22);
INSERT INTO aliment_recette VALUES (76, 22);
INSERT INTO aliment_recette VALUES (18, 22);
INSERT INTO aliment_recette VALUES (19, 22);
INSERT INTO aliment_recette VALUES (74, 23);
INSERT INTO aliment_recette VALUES (75, 23);
INSERT INTO aliment_recette VALUES (10, 23);
INSERT INTO aliment_recette VALUES (4, 23);
INSERT INTO aliment_recette VALUES (90, 23);
INSERT INTO aliment_recette VALUES (37, 23);
INSERT INTO aliment_recette VALUES (17, 23);
INSERT INTO aliment_recette VALUES (18, 23);
INSERT INTO aliment_recette VALUES (19, 23);
INSERT INTO aliment_recette VALUES (67, 23);
INSERT INTO aliment_recette VALUES (68, 23);
INSERT INTO aliment_recette VALUES (69, 23);
INSERT INTO aliment_recette VALUES (118, 24);
INSERT INTO aliment_recette VALUES (67, 24);
INSERT INTO aliment_recette VALUES (119, 24);
INSERT INTO aliment_recette VALUES (32, 24);
INSERT INTO aliment_recette VALUES (120, 24);
INSERT INTO aliment_recette VALUES (0, 26);
INSERT INTO aliment_recette VALUES (4, 26);
INSERT INTO aliment_recette VALUES (21, 26);
INSERT INTO aliment_recette VALUES (122, 26);
INSERT INTO aliment_recette VALUES (17, 26);
INSERT INTO aliment_recette VALUES (18, 26);
INSERT INTO aliment_recette VALUES (19, 26);
INSERT INTO aliment_recette VALUES (125, 26);
INSERT INTO aliment_recette VALUES (15, 27);
INSERT INTO aliment_recette VALUES (43, 27);
INSERT INTO aliment_recette VALUES (48, 27);
INSERT INTO aliment_recette VALUES (45, 27);
INSERT INTO aliment_recette VALUES (46, 27);
INSERT INTO aliment_recette VALUES (17, 27);
INSERT INTO aliment_recette VALUES (37, 27);
INSERT INTO aliment_recette VALUES (18, 27);
INSERT INTO aliment_recette VALUES (19, 27);
INSERT INTO aliment_recette VALUES (127, 27);
INSERT INTO aliment_recette VALUES (11, 28);
INSERT INTO aliment_recette VALUES (10, 28);
INSERT INTO aliment_recette VALUES (129, 28);
INSERT INTO aliment_recette VALUES (50, 28);
INSERT INTO aliment_recette VALUES (51, 28);
INSERT INTO aliment_recette VALUES (49, 28);
INSERT INTO aliment_recette VALUES (67, 28);
INSERT INTO aliment_recette VALUES (32, 28);
INSERT INTO aliment_recette VALUES (58, 28);
INSERT INTO aliment_recette VALUES (3, 29);
INSERT INTO aliment_recette VALUES (4, 29);
INSERT INTO aliment_recette VALUES (9, 29);
INSERT INTO aliment_recette VALUES (35, 29);
INSERT INTO aliment_recette VALUES (14, 29);
INSERT INTO aliment_recette VALUES (34, 29);
INSERT INTO aliment_recette VALUES (38, 29);
INSERT INTO aliment_recette VALUES (18, 29);
INSERT INTO aliment_recette VALUES (19, 29);
INSERT INTO aliment_recette VALUES (53, 29);
INSERT INTO aliment_recette VALUES (93, 30);
INSERT INTO aliment_recette VALUES (30, 30);
INSERT INTO aliment_recette VALUES (67, 30);
INSERT INTO aliment_recette VALUES (32, 30);
INSERT INTO aliment_recette VALUES (41, 30);
INSERT INTO aliment_recette VALUES (124, 30);
INSERT INTO aliment_recette VALUES (3, 31);
INSERT INTO aliment_recette VALUES (67, 31);
INSERT INTO aliment_recette VALUES (74, 31);
INSERT INTO aliment_recette VALUES (32, 31);
INSERT INTO aliment_recette VALUES (76, 31);
INSERT INTO aliment_recette VALUES (18, 31);
INSERT INTO aliment_recette VALUES (19, 31);
INSERT INTO aliment_recette VALUES (27, 31);
INSERT INTO aliment_recette VALUES (3, 32);
INSERT INTO aliment_recette VALUES (74, 32);
INSERT INTO aliment_recette VALUES (75, 32);
INSERT INTO aliment_recette VALUES (10, 32);
INSERT INTO aliment_recette VALUES (4, 32);
INSERT INTO aliment_recette VALUES (37, 32);
INSERT INTO aliment_recette VALUES (17, 32);
INSERT INTO aliment_recette VALUES (18, 32);
INSERT INTO aliment_recette VALUES (19, 32);
INSERT INTO aliment_recette VALUES (14, 32);
INSERT INTO aliment_recette VALUES (68, 32);

-- Ajout des diètes

INSERT INTO diete VALUES (0, 'Omnivore');
INSERT INTO diete VALUES (1, 'Végétarienne');
INSERT INTO diete VALUES (2, 'Végétalienne');
INSERT INTO diete VALUES (3, 'Paléo');
INSERT INTO diete VALUES (4, 'Pesco-végétarienne');
INSERT INTO diete VALUES (5, 'Ovo-lacto-végétarienne');
INSERT INTO diete VALUES (6, 'Lacto-végétarisme');

-- Ajout des diètes avec les recettes

INSERT INTO recette_diete VALUES (0, 0);
INSERT INTO recette_diete VALUES (1, 0);
INSERT INTO recette_diete VALUES (1, 1);
INSERT INTO recette_diete VALUES (1, 4);
INSERT INTO recette_diete VALUES (1, 5);
INSERT INTO recette_diete VALUES (1, 6);
INSERT INTO recette_diete VALUES (2, 0);
INSERT INTO recette_diete VALUES (3, 0);
INSERT INTO recette_diete VALUES (3, 1);
INSERT INTO recette_diete VALUES (3, 4);
INSERT INTO recette_diete VALUES (3, 5);
INSERT INTO recette_diete VALUES (3, 6);
INSERT INTO recette_diete VALUES (4, 0);
INSERT INTO recette_diete VALUES (5, 0);
INSERT INTO recette_diete VALUES (5, 4);
INSERT INTO recette_diete VALUES (6, 0);
INSERT INTO recette_diete VALUES (7, 0);
INSERT INTO recette_diete VALUES (7, 1);
INSERT INTO recette_diete VALUES (7, 2);
INSERT INTO recette_diete VALUES (7, 3);
INSERT INTO recette_diete VALUES (7, 4);
INSERT INTO recette_diete VALUES (7, 5);
INSERT INTO recette_diete VALUES (7, 6);
INSERT INTO recette_diete VALUES (8, 0);
INSERT INTO recette_diete VALUES (8, 1);
INSERT INTO recette_diete VALUES (8, 2);
INSERT INTO recette_diete VALUES (9, 0);
INSERT INTO recette_diete VALUES (9, 1);
INSERT INTO recette_diete VALUES (9, 2);
INSERT INTO recette_diete VALUES (9, 3);
INSERT INTO recette_diete VALUES (9, 4);
INSERT INTO recette_diete VALUES (9, 5);
INSERT INTO recette_diete VALUES (9, 6);
INSERT INTO recette_diete VALUES (10, 0);
INSERT INTO recette_diete VALUES (10, 1);
INSERT INTO recette_diete VALUES (10, 4);
INSERT INTO recette_diete VALUES (10, 5);
INSERT INTO recette_diete VALUES (10, 6);
INSERT INTO recette_diete VALUES (11, 0);
INSERT INTO recette_diete VALUES (11, 1);
INSERT INTO recette_diete VALUES (11, 4);
INSERT INTO recette_diete VALUES (11, 5);
INSERT INTO recette_diete VALUES (12, 0);
INSERT INTO recette_diete VALUES (12, 1);
INSERT INTO recette_diete VALUES (12, 2);
INSERT INTO recette_diete VALUES (12, 4);
INSERT INTO recette_diete VALUES (12, 5);
INSERT INTO recette_diete VALUES (12, 6);
INSERT INTO recette_diete VALUES (13, 0);
INSERT INTO recette_diete VALUES (13, 1);
INSERT INTO recette_diete VALUES (13, 2);
INSERT INTO recette_diete VALUES (13, 4);
INSERT INTO recette_diete VALUES (13, 5);
INSERT INTO recette_diete VALUES (13, 6);
INSERT INTO recette_diete VALUES (14, 0);
INSERT INTO recette_diete VALUES (15, 0);
INSERT INTO recette_diete VALUES (15, 3);
INSERT INTO recette_diete VALUES (16, 0);
INSERT INTO recette_diete VALUES (16, 3);
INSERT INTO recette_diete VALUES (17, 0);
INSERT INTO recette_diete VALUES (17, 4);
INSERT INTO recette_diete VALUES (18, 0);
INSERT INTO recette_diete VALUES (18, 1);
INSERT INTO recette_diete VALUES (18, 2);
INSERT INTO recette_diete VALUES (18, 4);
INSERT INTO recette_diete VALUES (18, 5);
INSERT INTO recette_diete VALUES (19, 0);
INSERT INTO recette_diete VALUES (19, 3);
INSERT INTO recette_diete VALUES (19, 4);
INSERT INTO recette_diete VALUES (20, 0);
INSERT INTO recette_diete VALUES (20, 1);
INSERT INTO recette_diete VALUES (20, 2);
INSERT INTO recette_diete VALUES (20, 4);
INSERT INTO recette_diete VALUES (20, 5);
INSERT INTO recette_diete VALUES (20, 6);
INSERT INTO recette_diete VALUES (21, 0);
INSERT INTO recette_diete VALUES (21, 3);
INSERT INTO recette_diete VALUES (22, 0);
INSERT INTO recette_diete VALUES (23, 0);
INSERT INTO recette_diete VALUES (23, 1);
INSERT INTO recette_diete VALUES (23, 2);
INSERT INTO recette_diete VALUES (23, 3);
INSERT INTO recette_diete VALUES (23, 4);
INSERT INTO recette_diete VALUES (23, 5);
INSERT INTO recette_diete VALUES (23, 6);
INSERT INTO recette_diete VALUES (24, 0);
INSERT INTO recette_diete VALUES (24, 3);
INSERT INTO recette_diete VALUES (24, 4);
INSERT INTO recette_diete VALUES (26, 0);
INSERT INTO recette_diete VALUES (26, 1);
INSERT INTO recette_diete VALUES (26, 2);
INSERT INTO recette_diete VALUES (26, 4);
INSERT INTO recette_diete VALUES (26, 5);
INSERT INTO recette_diete VALUES (26, 6);
INSERT INTO recette_diete VALUES (27, 0);
INSERT INTO recette_diete VALUES (27, 1);
INSERT INTO recette_diete VALUES (27, 3);
INSERT INTO recette_diete VALUES (27, 4);
INSERT INTO recette_diete VALUES (27, 5);
INSERT INTO recette_diete VALUES (27, 6);
INSERT INTO recette_diete VALUES (28, 0);
INSERT INTO recette_diete VALUES (29, 0);
INSERT INTO recette_diete VALUES (30, 0);
INSERT INTO recette_diete VALUES (31, 0);
INSERT INTO recette_diete VALUES (32, 3);
INSERT INTO recette_diete VALUES (32, 0);

-- Ajout des Allergie

INSERT INTO Client_Allergie VALUES (0,'Arachide');
INSERT INTO Client_Allergie VALUES (1,'Lactose');
INSERT INTO Client_Allergie VALUES (2,'Gluten');
INSERT INTO Client_Allergie VALUES (3,'Poisson');
INSERT INTO Client_Allergie VALUES (4,'Fruit de mer');
INSERT INTO Client_Allergie VALUES (5,'Oeuf');
INSERT INTO Client_Allergie VALUES (6,'Soja');
INSERT INTO Client_Allergie VALUES (7,'Sesame');

